jobs: <max number of jobs, I use 50>
cluster: "sbatch -p <partition> -t {resources.time_min} --mem={resources.mem_mb} -c {resources.cpus} -o logs_slurm/{rule}_{wildcards} -e logs_slurm/{rule}_{wildcards} --mail-type=FAIL --mail-user=<username@domain.space>"
resources: [cpus=<max number of cpus>, mem_mb=<max amount of RAM>]
